### ISSUE TITLE
drop annotation store calls for annotatorjs

### ISSUE THREAD

**Issue by nmaekawa** [lduarte1991/Hxighlighter#40]
To completely drop annotators:
- use "Authorization: token <jwt>" header instead of "Annotator_auth_token: <jwt>"
- replace "contextId" with "context-id" in search requests
- replace "collectionId" with "collection-id" in search requests

---

**Comment by lduarte1991** [comment]
This was changed in v1.5.0
https://github.com/lduarte1991/Hxighlighter/blob/v1.5.0/src/js/storage/catchpy.js#L75### 

In terms of contextId/collectionId, we discussed that this was due to changes in hxat and not Hxighlighter.
